INSERT INTO ARTICLES (NAME, DESCRIPTION, ADDITIONAL_VALUES) VALUES ('Ball','Grüner Ball','{}');
INSERT INTO ARTICLES (NAME, DESCRIPTION, ADDITIONAL_VALUES) VALUES ('Stirnband','Rotes Stirnband','{}');
INSERT INTO ARTICLES (NAME, DESCRIPTION, ADDITIONAL_VALUES) VALUES ('Flasche','Flasche mit Deckel der nur einmal abgeht','{}');
INSERT INTO ARTICLES (NAME, DESCRIPTION, ADDITIONAL_VALUES) VALUES ('Laptop','Laptop mit KI in der Hardware','{}');
INSERT INTO ARTICLES (NAME, DESCRIPTION, ADDITIONAL_VALUES) VALUES ('Tisch','Tisch mit runden Kanten','{}');

INSERT INTO SERVICES (DESCRIPTION, NAME, AVAILABLE, PRICE, ADDITIONAL_VALUES) VALUES ('Massage ohne Happy End', 'Massage', true,1.99, '{}' );
INSERT INTO SERVICES (DESCRIPTION, NAME, AVAILABLE, PRICE, ADDITIONAL_VALUES) VALUES ('Tisch putzen', 'Putzen', true,7.99, '{}' );
INSERT INTO SERVICES (DESCRIPTION, NAME, AVAILABLE, PRICE, ADDITIONAL_VALUES) VALUES ('Boden putzen', 'Putzen', false,100.99, '{}' );
INSERT INTO SERVICES (DESCRIPTION, NAME, AVAILABLE, PRICE, ADDITIONAL_VALUES) VALUES ('TÜV Prüfung', 'TÜV', true,19.99, '{}' );
INSERT INTO SERVICES (DESCRIPTION, NAME, AVAILABLE, PRICE, ADDITIONAL_VALUES) VALUES ('Stühle schleppen hin und her', 'Stühle schleppen', false,2.00, '{}' );

INSERT INTO DEPOSITORY_SPOTS (ROW_NR, COLUMN_NR) VALUES (1, 2);
INSERT INTO DEPOSITORY_SPOTS (ROW_NR, COLUMN_NR) VALUES (2, 2);
INSERT INTO DEPOSITORY_SPOTS (ROW_NR, COLUMN_NR) VALUES (1, 1);
INSERT INTO DEPOSITORY_SPOTS (ROW_NR, COLUMN_NR) VALUES (10, 10);
INSERT INTO DEPOSITORY_SPOTS (ROW_NR, COLUMN_NR) VALUES (23, 1);

INSERT INTO ARTICLE_ITEMS (ARTICLE_ID, SPOT_ID, SELL_PRICE, BUY_PRICE, AMOUNT) VALUES (1, 1, 3.99, 4.99, 100);
INSERT INTO ARTICLE_ITEMS (ARTICLE_ID, SPOT_ID, SELL_PRICE, BUY_PRICE, AMOUNT) VALUES (1, null, 30.99, 40.99, 100);
INSERT INTO ARTICLE_ITEMS (ARTICLE_ID, SPOT_ID, SELL_PRICE, BUY_PRICE, AMOUNT) VALUES (2, 2, 30.99, 49.99, 1000);
INSERT INTO ARTICLE_ITEMS (ARTICLE_ID, SPOT_ID, SELL_PRICE, BUY_PRICE, AMOUNT) VALUES (3, 3, 322.99, 43.99, 10);
INSERT INTO ARTICLE_ITEMS (ARTICLE_ID, SPOT_ID, SELL_PRICE, BUY_PRICE, AMOUNT) VALUES (4, 4, 387.99, 44.99, 4200);
INSERT INTO ARTICLE_ITEMS (ARTICLE_ID, SPOT_ID, SELL_PRICE, BUY_PRICE, AMOUNT) VALUES (5, 5, 787.99, 40.99, 69);